bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 2
              unit: seconds
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}